<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<title>libexcept: Limitations</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td style="padding-left: 0.5em;">
   <div id="projectname">libexcept
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.1.2 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li class="current"><a href="pages.html"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
    </ul>
  </div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">Limitations </div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><p>Although it is possible to get a fairly functional exceptions framework using standard ANSI C, there are limitations to the system. This page documents things that cannot be done with libexcept.</p>
<h1><a class="anchor" id="breakout"></a>
Breaking out of an exception block</h1>
<p>It is not possible to break out of an exception block using continue, break, return or goto. libexcept has built-in guards that detect when this is done. The following example demonstrates illegal usage:</p>
<div class="fragment"><div class="line"><span class="keywordtype">void</span> illegal(<span class="keywordtype">void</span>)</div>
<div class="line">{</div>
<div class="line">    <span class="keywordtype">int</span> i;</div>
<div class="line"></div>
<div class="line">    <span class="keywordflow">for</span> (i=0; i&lt;10; ++i) {</div>
<div class="line">        except_try {</div>
<div class="line">            <span class="comment">/* Illegal: cannot use break to exit out of an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">break</span>;</div>
<div class="line">        </div>
<div class="line">            <span class="comment">/* Illegal: cannot use continue to exit out of an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">continue</span>;</div>
<div class="line"></div>
<div class="line">            <span class="comment">/* Illegal: cannot return from within an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">return</span>;</div>
<div class="line"></div>
<div class="line">            <span class="comment">/* Illegal: do not use goto to break out of an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">goto</span> label;</div>
<div class="line">        } except_end</div>
<div class="line"></div>
<div class="line">    label:</div>
<div class="line">    }</div>
<div class="line">}</div>
</div><!-- fragment --><p>However, the following is legal:</p>
<div class="fragment"><div class="line"><span class="keywordtype">void</span> legal(<span class="keywordtype">void</span>)</div>
<div class="line">{</div>
<div class="line">    <span class="keywordtype">int</span> i;</div>
<div class="line"></div>
<div class="line">    except_try {</div>
<div class="line">        <span class="keywordflow">for</span> (i=0; i&lt;10; ++i) {</div>
<div class="line">            <span class="comment">/* Legal: Can use break to exit a loop within an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">break</span>;</div>
<div class="line">        </div>
<div class="line">            <span class="comment">/* Legal: Can use continue within an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">continue</span>;</div>
<div class="line"></div>
<div class="line">            <span class="comment">/* Legal: Can use goto to jump within an exception block */</span></div>
<div class="line"></div>
<div class="line">            <span class="keywordflow">goto</span> label;</div>
<div class="line">        }</div>
<div class="line">        label:</div>
<div class="line">    } except_end</div>
<div class="line">}</div>
</div><!-- fragment --><p>Note: the same limitations also apply within catch and finally blocks.</p>
<h1><a class="anchor" id="nested"></a>
Nested exception blocks</h1>
<p>It is not possible to have an exception block within another exception block. The following is illegal:</p>
<div class="fragment"><div class="line"><span class="keywordtype">void</span> illegal(<span class="keywordtype">void</span>)</div>
<div class="line">{</div>
<div class="line">    except_try {</div>
<div class="line">        except_try {</div>
<div class="line">            printf(<span class="stringliteral">&quot;hello, world\n&quot;</span>);</div>
<div class="line">        } except_catch (CircleException, e) {</div>
<div class="line">            printf(<span class="stringliteral">&quot;Circle Exception caught!\n&quot;</span>);</div>
<div class="line">        }</div>
<div class="line">    } except_catch (SquareException, e) {</div>
<div class="line">        printf(<span class="stringliteral">&quot;Square Exception caught!\n&quot;</span>);</div>
<div class="line">    }</div>
<div class="line">}</div>
</div><!-- fragment --><p>However, the following is legal:</p>
<div class="fragment"><div class="line"><span class="keywordtype">void</span> legal_2(<span class="keywordtype">void</span>)</div>
<div class="line">{</div>
<div class="line">    except_try {</div>
<div class="line">        printf(<span class="stringliteral">&quot;hello, world\n&quot;</span>);</div>
<div class="line">    } except_catch (CircleException, e) {</div>
<div class="line">        printf(<span class="stringliteral">&quot;Circle Exception caught!\n&quot;</span>);</div>
<div class="line">    }</div>
<div class="line">}</div>
<div class="line"></div>
<div class="line"><span class="keywordtype">void</span> legal_1(<span class="keywordtype">void</span>)</div>
<div class="line">{</div>
<div class="line">    except_try {</div>
<div class="line">        legal_2();</div>
<div class="line">    } except_catch (SquareException, e) {</div>
<div class="line">        printf(<span class="stringliteral">&quot;Square Exception caught!\n&quot;</span>);</div>
<div class="line">    }</div>
<div class="line">}</div>
</div><!-- fragment --> </div></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Sat May 9 2015 03:40:56 for libexcept by &#160;<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/>
</a> 1.8.1.2
</small></address>
</body>
</html>
